baseURL = "https://d36.netlify.com"
googleAnalytics = "G-1MSQGC8M1F"
theme = "omega"
title = "D36.ch - digitally productive"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7
[[menu.main]]
name = "Career"
pre = ""
url = "career"
weight = 6
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[params]
author = "Themefisher"
contact_info = "D36.CH Sàrl <br> Chemin derrière les Vignes 23d <br> 1588 Cudrefin <br> Switzerland"
description = "This is meta description"
logo = "images/d36-logo.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "${{ GMAPS_API_KEY }}"
map_center_lat = "47.11079242069359"
map_center_lng = " 6.336883820692627"
map_marker = "images/map-marker.png"
map_position_lat = "46.95147816259209"
map_position_lng = "7.02686743208056"
[[params.social]]
icon = "fa-linkedin"
link = "#"
title = "linkedin"
