baseURL = "https://d36.netlify.com"
googleAnalytics = "G-1MSQGC8M1F"
theme = "omega"
title = "D36.ch - digitally productive"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 7
[[menu.main]]
name = "Career"
pre = ""
url = "career"
weight = 6
[[menu.main]]
name = "Solutions"
pre = "#"
url = "products"
weight = 3
[[menu.main]]
name = "About"
pre = "#"
url = "mission"
weight = 2
[[menu.main]]
name = "Home"
pre = ""
url = "/"
weight = 1
[params]
author = "Themefisher"
contact_info = "D36.CH Sàrl <br> Chemin derrière les Vignes 23d <br> 1588 Cudrefin <br> Switzerland"
description = "This is meta description"
logo = "images/d36-logo.png"
logo_width = "120px"
preloader = true
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "46.9549732"
map_center_lng = "6.9241081"
map_marker = "images/map-marker.png"
map_position_lat = "46.9549732"
map_position_lng = "6.9241081"
[[params.social]]
icon = "fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fa-twitter"
link = "#"
title = "twitter"
[[params.social]]
icon = "fa-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "fa-github"
link = "#"
title = "github"
[[params.social]]
icon = "fa-linkedin"
link = "#"
title = "linkedin"
